# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_location',
            field=models.CharField(default='defaultlocation', max_length=1000),
            preserve_default=False,
        ),
    ]
