# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=500)),
                ('first_name', models.CharField(max_length=200)),
                ('public_profile', models.CharField(max_length=2000)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
