# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20180110_0139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
